// Import db.js
const db = require('../db')
// Import mongoose from node_modules
const mongoose = require('mongoose')

let schema = mongoose.Schema
let ObjectId = schema.Types.ObjectId

// create booking schema
var booking = new schema (
	{
		service:{
			type: String
		},
		price: {
			type: Number
		},
		date: {
			type: Date
		},
		starttime: {
			type: Date
		},
		endtime: {
			type: Date
		},
		duration: {
			type: Number
		}

	}
)

// Create schema for customer
const db_customer = db.model('customer', {
	__v: {
		type: Number,
		select: false
	},
	firstname: {
		type: String,
		required: true
	},
	lastname: {
		type: String,
		required: true
	},
	email: {
		type: String,
		required: true,
		validate: [
			{
				validator: function(email) {
					return email.length > 6
				},
				message: 'email must be 7 characters minimum'
			}
		]
	},
	password: {
		type: String,
		required: true
	},
	created: {
		type: Date,
		required: true,
		default: Date.now
	},
	// It is going to be a token generated by stripe
	cardnumber: {
		type: Number
	},
	expiration: {
		type: Date
	},
	cvc: {
		type: Number
	},
	booking: {
		type:[booking]
	}
	
	
})

// Export
module.exports = db_customer
